apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-lb
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: haproxy-lb
  template:
    metadata:
      labels:
        app: haproxy-lb
    spec:
      containers:
      - name: haproxy-lb
        image: haproxy
#        args: 
#        - --net=host
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy
          name: config
        - mountPath: /etc/ssl/private
          name: certs
        ports:
          - name: http
            containerPort: 5000
          - name: https
            containerPort: 5443
      volumes:
        - name: config
          hostPath:
            path: /etc/haproxy
            type: Directory
        - name: certs
          hostPath:
            path: /etc/ssl/private
            type: Directory

