---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-lb
  namespace: default
spec:
  type: NodePort
  ports:
  - name: port-http
    port: 5000
    nodePort: 32080
    targetPort: 5000
  - name: port-https
    port: 5443
    nodePort: 32443
    targetPort: 5443
  selector:
    app: haproxy-lb

